import type { Plan, PlanFeature } from "./billing.types";

// Which plans can access each feature
export const FEATURE_PLANS: Record<PlanFeature, Plan[]> = {
  automation: ["TRIAL", "GROWTH", "BUSINESS", "ENTERPRISE"],
  flowBuilder: ["TRIAL", "GROWTH", "BUSINESS", "ENTERPRISE"],
  aiChatbot: ["TRIAL", "GROWTH", "BUSINESS", "ENTERPRISE"],
  apiAccess: ["TRIAL", "GROWTH", "BUSINESS", "ENTERPRISE"],
  advancedAnalytics: ["TRIAL", "GROWTH", "BUSINESS", "ENTERPRISE"],
  teamManagement: ["TRIAL", "STARTER", "GROWTH", "BUSINESS", "ENTERPRISE"],
};

// Human-readable upgrade message per feature
export const FEATURE_UPGRADE_MESSAGE: Record<PlanFeature, string> = {
  automation: "Automation rules require Growth plan or above",
  flowBuilder: "Flow Builder requires Growth plan or above",
  aiChatbot: "AI Chatbot requires Growth plan or above",
  apiAccess: "API access requires Growth plan or above",
  advancedAnalytics: "Advanced analytics require Growth plan or above",
  teamManagement: "Team management is available on all plans",
};

export const PLAN_LIMITS = {
  TRIAL: {
    teamMembers: 10,
    contacts: 25000,
    whatsappNumbers: 2,
    aiSessions: 500,
    flowBuilder: true,
    aiChatbot: true,
    apiAccess: true,
  },
  STARTER: {
    teamMembers: 3,
    contacts: 5000,
    whatsappNumbers: 1,
    aiSessions: 0,
    flowBuilder: false,
    aiChatbot: false,
    apiAccess: false,
  },
  GROWTH: {
    teamMembers: 10,
    contacts: 25000,
    whatsappNumbers: 2,
    aiSessions: 500,
    flowBuilder: true,
    aiChatbot: true,
    apiAccess: true,
  },
  BUSINESS: {
    teamMembers: 25,
    contacts: 100000,
    whatsappNumbers: 5,
    aiSessions: 5000,
    flowBuilder: true,
    aiChatbot: true,
    apiAccess: true,
  },
  ENTERPRISE: {
    teamMembers: -1,
    contacts: -1,
    whatsappNumbers: -1,
    aiSessions: -1,
    flowBuilder: true,
    aiChatbot: true,
    apiAccess: true,
  },
};

export const PLAN_PRICING = [
  {
    id: "STARTER",
    name: "Starter",
    desc: "Perfect to explore and get started with WhatsApp API.",
    badge: "14-Day Trial",
    highlight: false,
    cta: "Start Free",
    ctaHref: "https://app.macropage.in/register",
    currency: "INR",
    pricing: {
      monthly: { price: 1999, billedAs: "₹1,999/month" },
      quarterly: {
        price: 1799,
        billedAs: "₹5,397 every 3 months",
        savings: "Save 10%",
      },
      yearly: { price: 1499, billedAs: "₹17,988/year", savings: "Save 25%" },
    },
    features: [
      "1 WhatsApp Business Number",
      "Up to 1,000 messages/month",
      "Basic Chatbot Builder",
      "Shared Team Inbox",
      "Message Templates (5)",
      "Basic Analytics",
      "Email Support",
    ],
    notIncluded: [
      "Bulk Broadcasts",
      "CRM Integration",
      "API Access",
      "Dedicated Manager",
    ],
  },
  {
    id: "GROWTH",
    name: "Growth",
    desc: "For growing businesses ready to scale their WhatsApp marketing.",
    badge: "Most Popular",
    highlight: true,
    cta: "Start Free Trial",
    ctaHref: "https://app.macropage.in/register",
    currency: "INR",
    pricing: {
      monthly: { price: 3499, billedAs: "₹3,499/month" },
      quarterly: {
        price: 3149,
        billedAs: "₹9,447 every 3 months",
        savings: "Save 10%",
      },
      yearly: { price: 2624, billedAs: "₹31,488/year", savings: "Save 25%" },
    },
    features: [
      "3 WhatsApp Business Numbers",
      "Up to 25,000 messages/month",
      "Advanced Chatbot & Flows",
      "Team Inbox (5 agents)",
      "Unlimited Templates",
      "Bulk Broadcast Campaigns",
      "Basic CRM Integration",
      "Full Analytics Dashboard",
      "Priority Email & Chat Support",
    ],
    notIncluded: ["Dedicated Manager", "Custom API Rate Limits"],
  },
  {
    id: "BUSINESS",
    name: "Scale",
    desc: "For established businesses that need enterprise-grade power.",
    badge: null,
    highlight: false,
    cta: "Start Free Trial",
    ctaHref: "https://app.macropage.in/register",
    currency: "INR",
    pricing: {
      monthly: { price: 8999, billedAs: "₹8,999/month" },
      quarterly: {
        price: 8099,
        billedAs: "₹24,297 every 3 months",
        savings: "Save 10%",
      },
      yearly: { price: 6749, billedAs: "₹80,988/year", savings: "Save 25%" },
    },
    features: [
      "Unlimited WhatsApp Numbers",
      "Unlimited Messages",
      "Full Automation Suite",
      "Unlimited Agents",
      "Unlimited Templates",
      "Bulk Broadcasts + Scheduling",
      "Full CRM & API Integration",
      "Advanced Analytics & Reports",
      "Webhooks & Custom Integrations",
      "Dedicated Account Manager",
      "SLA-backed Uptime",
    ],
    notIncluded: [],
  },
  {
    id: "ENTERPRISE",
    name: "Enterprise",
    desc: "Custom solutions for large teams with advanced needs.",
    badge: null,
    highlight: false,
    cta: "Contact Sales",
    ctaHref: "mailto:sales@macropage.in",
    currency: "INR",
    custom: true,
    pricing: {
      monthly: { price: 0, billedAs: "Custom pricing" },
      quarterly: { price: 0, billedAs: "Custom pricing" },
      yearly: { price: 0, billedAs: "Custom pricing" },
    },
    features: [
      "Everything in Scale",
      "Custom Integrations",
      "Dedicated Infrastructure",
      "Custom SLA",
      "Priority Onboarding",
    ],
    notIncluded: [],
  },
];
